services:
  - type: web
    name: object-counter
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app --timeout 120"
    pythonVersion: "3.12.4"
    build:
      packages:
        - libgl1-mesa-glx
